arch = "amd64"

# where all nebula files are located
nebula-dir= "/tmp/nebula"

fakeroot-dir = "/tmp/nebula/pkgs"

# where the packages are going to be linked to (usually, /usr)
destination-dir = "/home/mike/proiektuak/lfs/nebula/testdir"

[repositories]

    [repositories.nebula]
    repository = "http://localhost:8080"

    [repositories.debian]
    # repository = "http://ftp.debian.org/debian/dists/unstable"
    repository = "http://deb.devuan.org/merged/dists/chimaera"
    components = ["main", "contrib"]
